return {}
-- return {
--   "yetone/avante.nvim",
--   build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
--     or "make",
--   event = "VeryLazy",
--   version = false,
--   ---@module 'avante'
--   ---@type avante.Config
--   opts = {
--     auto_suggestions_provider = "copilot",
--     instructions_file = "avante.md",
--     provider = "openai",
--     providers = {
--       claude = {
--         endpoint = "https://api.anthropic.com",
--         model = "claude-sonnet-4-20250514",
--         timeout = 30000,
--         extra_request_body = {
--           temperature = 0.75,
--           max_tokens = 20480,
--         },
--       },
--       openai = {
--         endpoint = "https://api.openai.com/v1",
--         model = "gpt-5",
--         timeout = 30000,
--         extra_request_body = {
--           temperature = 1,
--           max_completion_tokens = 16384,
--         },
--       },
--     },
--     behaviour = {
--       auto_suggestions = false,
--     },
--   },
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     "folke/snacks.nvim",
--     "stevearc/dressing.nvim",
--     "nvim-tree/nvim-web-devicons",
--     "zbirenbaum/copilot.lua",
--     {
--       "HakonHarnes/img-clip.nvim",
--       event = "VeryLazy",
--       opts = {
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       "MeanderingProgrammer/render-markdown.nvim",
--       opts = {
--         file_types = { "markdown", "Avante" },
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
-- }
